server:
  port: 8080

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: orders
          uri: http://localhost:8081
          predicates:
            - Path=/api/orders/**
        - id: payments
          uri: http://localhost:8082
          predicates:
            - Path=/api/payments/**
        - id: products
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**

eureka:
  client:
    register-with-eureka: false